on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  main:
    name: Deploy to GitHub pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install and update Bikeshed
        run: pip3 install bikeshed && bikeshed update
        shell: bash
      - name: Build spec
        run: bash ./compile.sh
        shell: bash
